{% set name = "act" %}
{% set version = "0.97" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - path: ../..
    folder: ACT
  - git_url: https://github.com/dspoel/openbabel.git
    folder: openbabel

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - make
    - openmpi
    - graphviz
    - cmake
    - cairo
    - fftw
    - eigen
    - libxml2
    - swig
    - sqlite
    - doxygen
  host:
    - python
  run:
    - openmpi
    - matplotlib
    - pubchempy
    - numpy
    - cairo
    - graphviz
    # - cmake
    - fftw
    - eigen
    - libxml2
    - swig
    - sqlite
    - doxygen
  run_constrained:
    - python>=3.10

about:
  home: https://github.com/dspoel/ACT
  license: MIT
  summary: 'Global optimization of force fields for molecular simulation'
  doc_url: https://github.com/dspoel/ACT/wiki
