language: cpp

before_install:
 - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake #https://github.com/travis-ci/travis-ci/issues/2212
 - sudo apt-get update
 - sudo apt-get install libfftw3-dev libopenmpi-dev libx11-dev zlib1g-dev libgsl0-dev libxml2-dev libblas-dev liblapack-dev libboost-dev cmake

env:
  matrix:
    - GMX_DOUBLE=ON  GMX_MPI=ON

script: 
  - mkdir build && pushd build && cmake -DGMX_DOUBLE=ON -DGMX_MPI=ON -DGMX_X11=OFF -DBUILD_SHARED_LIBS=OFF -DGMX_OPENMP=OFF  -DGMX_DEFAULT_SUFFIX=OFF -DGMX_LIBXML2=ON -DGMX_COMPACT_DOXYGEN=ON  .. && make -j4

compiler:
  - clang
  - gcc

after_success:
  # Generate the docs only if master, the travis_build_docs is true and we can use secure variables
  - >-
    if [[ "$TRAVIS_BRANCH" = "main" && -n "$TRAVIS_BUILD_DOCS" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
      cd $PROJECT_DIR_ABS
      source .ci/setup-ssh.sh || travis_terminate 1
      .ci/generateDocumentation.sh || travis_terminate 1
    fi