#!/usr/bin/env python3

import os, shutil, argparse, subprocess, sys, glob, struct
from subprocess import Popen, PIPE

debug = False

def get_lib_suffix() -> str:
    if 64 == struct.calcsize("P") * 8:
        return "64"
    else:
        return ""

def get_host() -> str:
    '''Utility to get a string describing the build system'''
    if "HOST" in os.environ:
        HOST = os.environ["HOST"]
    elif "SNIC_SITE" in os.environ:
        HOST = os.environ["SNIC_SITE"]
    else:
        HOST = sys.platform
    return HOST

def get_compilers(ostype: str):
    '''Utility to return the C and C++ compiler respectively'''
    if "darwin" in ostype or "mac" in ostype:
        CXX = shutil.which("clang++")
        CC  = shutil.which("clang")
    else:
        CXX = None
        for cxxtry in [ "g++", "cxx", "ccc", "gcc" ]:
            CXX = shutil.which(cxxtry)
            if CXX:
                break
        for cctry in [ "gcc", "cc" ]:
            CC  = shutil.which(cctry)
            if CC:
                break
    if not CC or not CXX:
        sys.exit("Cannot find compilers")
    return CC, CXX

def get_mpirun():
    for mrun in [ "srun", "mpirun" ]:
        mpirun = shutil.which(mrun)
        if mpirun:
            return mpirun
    return None

def get_prefix(myprefix):
    cpp  = "CMAKE_PREFIX_PATH"
    cinc = "CPLUS_INCLUDE_PATH"
    conda = "CONDA_PREFIX"
    prefix = []
    if cpp in os.environ:
        prefix = os.environ[cpp].split(":")
    elif cinc in os.environ:
        for inc in os.environ[cinc].split(":"):
            # Add the directory excluding the /include part
            prefix.append(inc[:-8])
    elif conda in os.environ:
        prefix.append(os.environ[conda])
    else:
        conda = shutil.which("conda")
        if conda and len(conda) > 10:
            prefix = [ conda[:-10] ]
    if len(prefix) == 0:
        return ""
    else:
        pp = ""
        if len(prefix[0]) > 0:
            pp = prefix[0]
        if myprefix and len(myprefix) > 0:
            pp += ";" + myprefix
        for p in range(1, len(prefix)):
            if len(pp) > 0:
                pp += ";"
            pp += prefix[p]
        return pp.lstrip(';')
    
def find_lib(prefix, libname, verbose):
    if verbose:
        print('Entering find_lib...')
        print(f'prefix: {prefix}')
        print(f'libname: {libname}')
    for pp in prefix.split(";"):
        libtry = pp+"/lib/"+libname
        if os.path.exists(libtry):
            if verbose:
                print('Leaving find_lib...')
            return libtry
    libpath = "LIBRARY_PATH"
    if libpath in os.environ:
        for pp in os.environ[libpath].split(":"):
            libtry = pp+"/"+libname
            if os.path.exists(libtry):
                return libtry
    sys.exit("Cannot find %s" % libname)

def run_command(command, flags):
    mycommand = shutil.which(command)
    if not mycommand or len(mycommand) == 0:
        sys.exit("Cannot find the '%s' program" % command)
    cmdlist = [ mycommand ] + flags.split()
    with Popen(cmdlist, stdout=PIPE, stderr=PIPE, stdin=PIPE) as p:
        output, error = p.communicate()
        with open(command+".out", "w") as outf:
            for line in output.decode('utf-8').splitlines():
                outf.write("%s\n" % line)
        with open(command+".err", "w") as outf:
            for line in error.decode('utf-8').splitlines():
                outf.write("%s\n" % line)

def install_act(args, CXX, CC, HOST, prefix):
    # Get working directory
    pwd = os.getcwd()
    swdir = "ACT"
        
    if args.clone_ACT:
        if os.path.isdir(swdir):
            print("Will not clone since directory %s exists. Will git pull instead" % swdir)
            os.chdir(swdir)
            run_command("git", "pull")
        else:
            if args.anonymous:
                os.system("git clone https://github.com/dspoel/ACT.git")
            else:
                os.system("git clone git@github.com:dspoel/ACT.git")
            if not os.path.isdir(swdir):
                sys.exit("No directory %s. Maybe you want to use the -clone_ACT flag" % swdir)
            os.chdir(swdir)
        os.system("git pull")
    else:
        actversion = "1.1b"
        actlatest = ( "v%s.tar.gz" % actversion )
        url       = "https://github.com/AlexandriaChemistry/ACT/archive/refs/tags"
        os.system("curl -L %s/%s -o %s" % ( url, actlatest, actlatest ) )
        if not os.path.exists(actlatest):
            sys.exit("Failed to download %s" % actlatest)
        os.system("tar xzf %s" % actlatest)
        swdir = "ACT-" + actversion
        os.chdir(swdir)


    PPATH  = prefix + ";" + args.destination
        
    # Construct cmake flags
    FLAGS = ("-DMPIEXEC=%s -DMPIEXEC_NUMPROC_FLAG='-n' -DBUILD_SHARED_LIBS=OFF -DGMX_OPENMP=OFF -DGMX_MPI=ON -DCMAKE_INSTALL_PREFIX=%s -DCMAKE_CXX_COMPILER=%s -DCMAKE_C_COMPILER=%s -DCMAKE_BUILD_TYPE=%s -DCMAKE_PREFIX_PATH='%s' -DACT_BUILD_MANUAL=OFF -DACT_COMPACT_DOXYGEN=ON -DGMX_DEFAULT_SUFFIX=OFF" % ( get_mpirun(), args.destination, CXX, CC, args.build, PPATH ) )
    if args.cln:
        FLAGS += " -DGMX_CLN=ON"

    # Make correct build directory
    bdir = "build_" + args.build
    if not args.single:
        FLAGS += " -DGMX_DOUBLE=ON"
        bdir = bdir + "_DOUBLE"
    if args.verbose:
        print("Will create %s" % bdir)
    os.makedirs(bdir, exist_ok=True)
    os.chdir(bdir)
    if args.verbose:
        print("install_act cmake FLAGS: %s in directory %s" % ( FLAGS, os.getcwd() ) )
    # Clean up old CMake stuff
    cmc = "CMakeCache.txt"
    if os.path.exists(cmc):
        os.unlink(cmc)
    # Run cmake and make!
    for ff in [ "make.err", "make.out", "cmake.out", "cmake.err" ]:
        if os.path.exists(ff):
            os.unlink(ff)
    alex = ("%s/bin/alexandria" % args.destination)
    if os.path.exists(alex):
        os.unlink(alex)
    run_command("cmake", FLAGS + " ..")
    run_command("make", (" -j %d install tests" % args.ncores))
    if not os.path.exists(alex):
        sys.exit("Could not build '%s', check cmake.* and make.* in %s" % ( alex, os.getcwd() ) )
    else:
        print("Succesfully installed ACT in %s/bin. Please source %s/bin/ACTRC to start using ACT." % ( args.destination, args.destination) )
    
    # Go back to where we came from
    os.chdir(pwd)
    
def parseArguments():
    desc='''This script will download and install the 
    Alexandria Chemistry Toolkit.
    '''
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument("-f", "--flags",  help="Additional compilation flags",type=str, default="")
    parser.add_argument("-anon", "--anonymous",  help="If you do not have an account at gitlab.com (gromacs) or github.com (ACT) select this option.", action="store_true")
    parser.add_argument("-clone_ACT", "--clone_ACT", help="Clone ACT git repository", action="store_true")
    parser.add_argument("-ncores","--ncores", help="Number of cores for compiling", type=int, default=8)
    parser.add_argument("-bt", "--build", help="Build type for cmake. Typically Release or Debug, but Profile and ASAN (Adress Sanitizer) are available as well.", type=str, default="Release")
    parser.add_argument("-single", "--single", help="Single precision build (will not work well)", action="store_true")
    parser.add_argument("-cln", "--cln", help="Use the Class Library for Numbers (optional)", action="store_true")
    parser.add_argument("-debug", "--debug", help="Print debugging information for the script", action="store_true")
    home = "HOME"
    if home in os.environ:
        dest = os.environ["HOME"]
    else:
        dest = "."
    dest += "/tools"
    parser.add_argument("-dest", "--destination", help="Where to install the software. Default: "+dest , type=str, default=dest)
    parser.add_argument("-prefix", "--prefix", help="Directory where libraries are installed, default autodetect", type=str, default=None)
    parser.add_argument("-v", "--verbose", help="Print more stuff on the terminal", action="store_true")
    
    args = parser.parse_args()
    return args

if __name__ == '__main__':
    args    = parseArguments()
    
    HOST    = get_host()
    CC, CXX = get_compilers(HOST)
    SW      = get_prefix(args.prefix)
    # Remove duplicates from SW
    SW = ';'.join(list(set(SW.split(';'))))
    debug = args.debug
    if args.verbose:
        print("HOST = %s" % HOST)
        print("CC   = %s" % CC)
        print("CXX  = %s" % CXX)
    if debug:
        print("args.prefix = %s SW = '%s'" % ( args.prefix, SW ))

    install_act(args, CXX, CC, HOST, SW)
